# Generated by Django 2.1.8 on 2019-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recognize_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='识别种类id')),
                ('name', models.CharField(choices=[(0, '文字识别'), (1, '动物识别'), (2, '植物识别')], max_length=20, verbose_name='识别种类名称')),
                ('description', models.CharField(max_length=50, verbose_name='识别种类miaoshu')),
            ],
            options={
                'verbose_name': '识别种类模型',
                'verbose_name_plural': '识别种类模型',
            },
        ),
    ]
