# Generated by Django 2.1.8 on 2019-05-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190514_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognize_model',
            name='name',
            field=models.CharField(choices=[('C文字识别', '文字识别'), ('A动物识别', '动物识别'), ('P植物识别', '植物识别')], max_length=20, verbose_name='识别种类名称'),
        ),
    ]
