# Generated by Django 2.1.7 on 2019-07-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190514_1541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recognize_model',
            table='Recognize_Model',
        ),
    ]
