# Generated by Django 2.1.8 on 2019-05-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='服务名称编号')),
                ('name', models.CharField(choices=[(0, '语音技术'), (1, '视觉技术'), (2, '自然语言处理')], max_length=20, verbose_name='服务名称')),
                ('description', models.CharField(max_length=50, verbose_name='服务名称描述')),
            ],
            options={
                'verbose_name': '服务名称',
                'verbose_name_plural': '服务名称',
            },
        ),
    ]
