# Generated by Django 2.1.8 on 2019-05-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_model',
            name='name',
            field=models.CharField(choices=[('语言技术', 'voice'), ('视觉技术', 'vision'), ('自然语言处理', 'nlp')], max_length=20, verbose_name='服务名称'),
        ),
    ]
